services:
  tracktor_fork:
    build: .
    container_name: tracktor
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: "0.0.0.0"
      PORT: "3000"
      DB_PATH: /data/tracktor.db
      LOG_LEVEL: info
      LOG_DIR: /data/logs
      UPLOADS_DIR: /data/uploads
      BODY_SIZE_LIMIT: Infinity
    volumes:
      # Using a Docker named volume instead of a host folder
      - tracktor_data:/data
    ports:
      - "127.0.0.1:54320:3000"

volumes:
  tracktor_data:
